### ISSUE TITLE
运行docker镜像报错

### ISSUE THREAD

**Issue by jcjrobert** [MeetWq/meme-generator#171]
docker日志如下：
10-25 09:05:37 [INFO] meme_generator.log | Config file path: /root/.config/meme_generator/config.toml
Form data requires "python-multipart" to be installed. 
You can install "python-multipart" with: 

pip install python-multipart

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/meme_generator/app.py", line 203, in <module>
    run_server()
  File "/app/meme_generator/app.py", line 192, in run_server
    register_routers()
  File "/app/meme_generator/app.py", line 186, in register_routers
    register_router(meme)
  File "/app/meme_generator/app.py", line 68, in register_router
    async def _(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 994, in decorator
    self.add_api_route(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 933, in add_api_route
    route = route_class(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 554, in __init__
    self.dependant = get_dependant(path=self.path_format, call=self.endpoint)
  File "/usr/local/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 277, in get_dependant
    param_details = analyze_param(
  File "/usr/local/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 474, in analyze_param
    ensure_multipart_is_installed()
  File "/usr/local/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 107, in ensure_multipart_is_installed
    raise RuntimeError(multipart_not_installed_error) from None
RuntimeError: Form data requires "python-multipart" to be installed. 
You can install "python-multipart" with: 

pip install python-multipart

**Comment by jcjrobert** [comment]
使用0.1.4的docker镜像运行正常

**Comment by jcjrobert** [comment]
最新版本可使用
