### ISSUE TITLE
求解

### ISSUE THREAD

**Issue by lIfutureIl** [MeetWq/meme-generator#36]
05-24 08:55:12 [INFO] meme_generator.log | Config file path: /root/.config/meme_generator/config.toml
root@VM-8-7-ubuntu:~# meme run
05-24 08:55:24 [INFO] meme_generator.log | Config file path: /root/.config/meme_generator/config.toml
05-24 08:55:24 [INFO] uvicorn.server | Started server process [961196]       05-24 08:55:24 [INFO] uvicorn.lifespan.on | Waiting for application startup.
05-24 08:55:24 [INFO] uvicorn.lifespan.on | Application startup complete.
05-24 08:55:24 [INFO] uvicorn.server | Uvicorn running on http://127.0.0.1:2233 (Press CTRL+C to quit)
05-24 08:55:32 [INFO] uvicorn.protocols.http.h11_impl | 127.0.0.1:37682 - "POST /memes/do/ HTTP/1.1" 404
05-24 08:56:00 [INFO] uvicorn.protocols.http.h11_impl | 127.0.0.1:50650 - "POST /memes/hammer/ HTTP/1.1" 200
05-24 08:56:07 [INFO] uvicorn.protocols.http.h11_impl | 127.0.0.1:50664 - "POST /memes/kirby_hammer/ HTTP/1.1" 200                                        05-24 08:56:20 [INFO] uvicorn.protocols.http.h11_impl | 127.0.0.1:42234 - "POST /memes/do/ HTTP/1.1" 404                                                  05-24 09:09:59 [INFO] uvicorn.protocols.http.h11_impl | 127.0.0.1:36290 - "POST /memes/do/ HTTP/1.1" 404                                                  05-24 09:13:55 [INFO] uvicorn.protocols.http.h11_impl | 127.0.0.1:50950 - "POST /memes/do/ HTTP/1.1" 404                                                  05-24 09:15:50 [INFO] uvicorn.protocols.http.h11_impl | 127.0.0.1:33684 - "POST /memes/do/ HTTP/1.1" 404                                                  05-24 09:17:41 [INFO] uvicorn.protocols.http.h11_impl | 127.0.0.1:60148 - "POST /memes/do/ HTTP/1.1" 404                                                  05-24 09:18:03 [INFO] uvicorn.protocols.http.h11_impl | 127.0.0.1:46042 - "POST /memes/do/ HTTP/1.1" 404                                                  05-24 09:18:07 [INFO] uvicorn.protocols.http.h11_impl | 127.0.0.1:46052 - "POST /memes/petpet/ HTTP/1.1" 200                                              ^C05-24 09:20:09 [INFO] uvicorn.server | Shutting down
05-24 09:20:10 [INFO] uvicorn.lifespan.on | Waiting for application shutdown.05-24 09:20:10 [INFO] uvicorn.lifespan.on | Application shutdown complete.
05-24 09:20:10 [INFO] uvicorn.server | Finished server process [961196]
root@VM-8-7-ubuntu:~# meme run
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/toml/decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "/usr/local/lib/python3.10/dist-packages/toml/decoder.py", line 778, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "/usr/local/lib/python3.10/dist-packages/toml/decoder.py", line 880, in load_value
    return (self.load_array(v), "array")
  File "/usr/local/lib/python3.10/dist-packages/toml/decoder.py", line 1026, in load_array
    nval, ntype = self.load_value(a[i])
  File "/usr/local/lib/python3.10/dist-packages/toml/decoder.py", line 910, in load_value
    raise ValueError("This float doesn't have a leading "
ValueError: This float doesn't have a leading digit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/meme", line 5, in <module>
    from meme_generator.cli import main
  File "/usr/local/lib/python3.10/dist-packages/meme_generator/__init__.py", line 3, in <module>
    from meme_generator.config import meme_config as config
  File "/usr/local/lib/python3.10/dist-packages/meme_generator/config.py", line 72, in <module>
    meme_config = Config.load()
  File "/usr/local/lib/python3.10/dist-packages/meme_generator/config.py", line 61, in load
    return cls.parse_obj(toml.load(config_file_path))
  File "/usr/local/lib/python3.10/dist-packages/toml/decoder.py", line 134, in load
    return loads(ffile.read(), _dict, decoder)
  File "/usr/local/lib/python3.10/dist-packages/toml/decoder.py", line 514, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: This float doesn't have a leading digit (line 3 column 1 char 46)
root@VM-8-7-ubuntu:~# meme run
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/toml/decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "/usr/local/lib/python3.10/dist-packages/toml/decoder.py", line 778, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "/usr/local/lib/python3.10/dist-packages/toml/decoder.py", line 880, in load_value
    return (self.load_array(v), "array")
  File "/usr/local/lib/python3.10/dist-packages/toml/decoder.py", line 1026, in load_array
    nval, ntype = self.load_value(a[i])
  File "/usr/local/lib/python3.10/dist-packages/toml/decoder.py", line 910, in load_value
    raise ValueError("This float doesn't have a leading "
ValueError: This float doesn't have a leading digit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/meme", line 5, in <module>
    from meme_generator.cli import main
  File "/usr/local/lib/python3.10/dist-packages/meme_generator/__init__.py", line 3, in <module>
    from meme_generator.config import meme_config as config
  File "/usr/local/lib/python3.10/dist-packages/meme_generator/config.py", line 72, in <module>
    meme_config = Config.load()
  File "/usr/local/lib/python3.10/dist-packages/meme_generator/config.py", line 61, in load
    return cls.parse_obj(toml.load(config_file_path))
  File "/usr/local/lib/python3.10/dist-packages/toml/decoder.py", line 134, in load
    return loads(ffile.read(), _dict, decoder)
  File "/usr/local/lib/python3.10/dist-packages/toml/decoder.py", line 514, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: This float doesn't have a leading digit (line 3 column 1 char 46)

**Comment by lIfutureIl** [comment]
删了配置文件就好了
