### ISSUE TITLE
资源下载报错

### ISSUE THREAD

**Issue by WindraiteLesd** [MeetWq/meme-generator#6]
执行meme download后报错
`2023-03-11 13:17:54.282 | INFO     | meme_generator.download:check_resources:59 - Downloading images ...
  0%|                                                                                         | 0/1117 [00:00<?, ?it/s]Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\lib\site-packages\meme_generator\download.py", line 74, in check_resources
    await task
  File "C:\ProgramData\miniconda3\lib\asyncio\tasks.py", line 614, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "C:\ProgramData\miniconda3\lib\site-packages\meme_generator\download.py", line 66, in download_image
    if content := await _download(client, url):
  File "C:\ProgramData\miniconda3\lib\site-packages\meme_generator\download.py", line 20, in _download
    async with semaphore:
  File "C:\ProgramData\miniconda3\lib\asyncio\locks.py", line 14, in __aenter__
    await self.acquire()
  File "C:\ProgramData\miniconda3\lib\asyncio\locks.py", line 413, in acquire
    await fut
RuntimeError: Task <Task pending name='Task-13' coro=<check_resources.<locals>.download_image() running at C:\ProgramData\miniconda3\lib\site-packages\meme_generator\download.py:66> cb=[as_completed.<locals>._on_completion() at C:\ProgramData\miniconda3\lib\asyncio\tasks.py:601]> got Future <Future pending> attached to a different loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\miniconda3\Scripts\meme.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\miniconda3\lib\site-packages\meme_generator\cli.py", line 186, in main
    loop.run_until_complete(check_resources())
  File "C:\ProgramData\miniconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\ProgramData\miniconda3\lib\site-packages\meme_generator\download.py", line 75, in check_resources
    pbar.update()
  File "C:\ProgramData\miniconda3\lib\site-packages\httpx\_client.py", line 2000, in __aexit__
    await proxy.__aexit__(exc_type, exc_value, traceback)
  File "C:\ProgramData\miniconda3\lib\site-packages\httpx\_transports\default.py", line 332, in __aexit__
    await self._pool.__aexit__(exc_type, exc_value, traceback)
  File "C:\ProgramData\miniconda3\lib\site-packages\httpcore\_async\connection_pool.py", line 326, in __aexit__
    await self.aclose()
  File "C:\ProgramData\miniconda3\lib\site-packages\httpcore\_async\connection_pool.py", line 312, in aclose
    raise RuntimeError(
RuntimeError: The connection pool was closed while 10 HTTP requests/responses were still in-flight.
  0%|                                                                                         | 0/1117 [00:00<?, ?it/s]`

**Comment by MeetWq** [comment]
已修复 4c03d1fc4c403828a4b17106e3c82957846f3ef3 ，请更新新版本
