### ISSUE TITLE
meme download时出错

### ISSUE THREAD

**Issue by apologyday** [MeetWq/meme-generator#90]
系统：windows2016 serve
python版本：3.12.2
报错：如图
![Uploading QQ图片20240310214654.png…]()

**Comment by apologyday** [comment]
图没发出去……重贴一下报错
C:\Users\Administrator>meme download
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python312\Scripts\meme.exe\__main__.py", line 4, in <module>
  File "C:\Program Files\Python312\Lib\site-packages\meme_generator\__init__.py", line 3, in <module>
    from meme_generator.config import meme_config as config
  File "C:\Program Files\Python312\Lib\site-packages\meme_generator\config.py", line 72, in <module>
    meme_config = Config.load()
                  ^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\meme_generator\config.py", line 61, in load
    return cls.parse_obj(toml.load(config_file_path))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\site-packages\toml\decoder.py", line 134, in load
    return loads(ffile.read(), _dict, decoder)
                 ^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 38: invalid continuation byte

**Comment by MeetWq** [comment]
看上去是配置文件编码不对，把配置文件删了试试

**Comment by apologyday** [comment]
> 看上去是配置文件编码不对，把配置文件删了试试

已解决，删掉后再meme download就可以了:)
