### ISSUE TITLE
使用 pip 安装时出错

### ISSUE THREAD

**Issue by a1232580** [MeetWq/meme-generator#91]
安装方法：pip install meme_generator
系统：Android 12 MI 8

```
Collecting matplotlib<4.0.0,>=3.0.0 (from pil-utils<0.2.0,>=0.1.8->meme_generator)
  Using cached matplotlib-3.8.3.tar.gz (35.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [126 lines of output]
      /data/data/com.termux/files/usr/tmp/pip-build-env-7agh9umj/overlay/lib/python3.11/site-packages/setuptools_scm/git.py:308: UserWarning: git archive did not support describe output
        warnings.warn("git archive did not support describe output")
      /data/data/com.termux/files/usr/tmp/pip-build-env-7agh9umj/overlay/lib/python3.11/site-packages/setuptools_scm/git.py:327: UserWarning: unprocessed git archival found (no export subst applied)
        warnings.warn("unprocessed git archival found (no export subst applied)")
      /data/data/com.termux/files/usr/tmp/pip-build-env-7agh9umj/overlay/lib/python3.11/site-packages/setuptools_scm/_integration/setuptools.py:90: UserWarning: version of matplotlib already set
        warnings.warn(f"version of {dist_name} already set")

      Edit mplsetup.cfg to change the build options; suppress output with --quiet.

      BUILDING MATPLOTLIB
            python: yes [3.11.8 (main, Feb 11 2024, 13:05:24) [Clang 17.0.2
                        (https://android.googlesource.com/toolchain/llvm-project
                        d9f89f4d1]
          platform: yes [linux]
             tests: no  [skipping due to configuration]
            macosx: no  [Mac OS-X only]

      running egg_info
      writing lib/matplotlib.egg-info/PKG-INFO
      writing dependency_links to lib/matplotlib.egg-info/dependency_links.txt
      writing requirements to lib/matplotlib.egg-info/requires.txt
      writing top-level names to lib/matplotlib.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-7agh9umj/overlay/lib/python3.11/site-packages/numpy/core/__init__.py", line 24, in <module>
          from . import multiarray
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-7agh9umj/overlay/lib/python3.11/site-packages/numpy/core/multiarray.py", line 10, in <module>
          from . import overrides
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-7agh9umj/overlay/lib/python3.11/site-packages/numpy/core/overrides.py", line 8, in <module>
          from numpy.core._multiarray_umath import (
      ImportError: dlopen failed: cannot locate symbol "PyExc_ValueError" referenced by "/data/data/com.termux/files/usr/tmp/pip-build-env-7agh9umj/overlay/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311.so"...

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-7agh9umj/overlay/lib/python3.11/site-packages/numpy/__init__.py", line 130, in <module>
          from numpy.__config__ import show as show_config
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-7agh9umj/overlay/lib/python3.11/site-packages/numpy/__config__.py", line 4, in <module>
          from numpy.core._multiarray_umath import (
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-7agh9umj/overlay/lib/python3.11/site-packages/numpy/core/__init__.py", line 50, in <module>
          raise ImportError(msg)
      ImportError:

      IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

      Importing the numpy C-extensions failed. This error can happen for
      many reasons, often due to issues with your setup or how NumPy was
      installed.

      We have compiled some common reasons and troubleshooting tips at:

          https://numpy.org/devdocs/user/troubleshooting-importerror.html

      Please note and check the following:

        * The Python version is: Python3.11 from "/data/data/com.termux/files/usr/bin/python3.11"
        * The NumPy version is: "1.26.4"

      and make sure that they are the versions you expect.
      Please carefully study the documentation linked above for further help.

      Original error was: dlopen failed: cannot locate symbol "PyExc_ValueError" referenced by "/data/data/com.termux/files/usr/tmp/pip-build-env-7agh9umj/overlay/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311.so"...


      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-7agh9umj/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-7agh9umj/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-7agh9umj/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 279, in <module>
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-7agh9umj/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-7agh9umj/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-7agh9umj/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-7agh9umj/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-7agh9umj/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-7agh9umj/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-7agh9umj/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-7agh9umj/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
          mm.run()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-7agh9umj/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 550, in run
          self.add_defaults()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-7agh9umj/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 588, in add_defaults
          sdist.add_defaults(self)
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-7agh9umj/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 102, in add_defaults
          super().add_defaults()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-7agh9umj/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-7agh9umj/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 335, in _add_defaults_ext
          build_ext = self.get_finalized_command('build_ext')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-7agh9umj/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-7agh9umj/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "<string>", line 80, in finalize_options
        File "<string>", line 80, in <listcomp>
        File "/data/data/com.termux/files/usr/tmp/pip-install-g1quez1t/matplotlib_ed26db1cdd974f10a89e29fa9e66262c/setupext.py", line 403, in get_extensions
          add_numpy_flags(ext)
        File "/data/data/com.termux/files/usr/tmp/pip-install-g1quez1t/matplotlib_ed26db1cdd974f10a89e29fa9e66262c/setupext.py", line 511, in add_numpy_flags
          import numpy as np
        File "/data/data/com.termux/files/usr/tmp/pip-build-env-7agh9umj/overlay/lib/python3.11/site-packages/numpy/__init__.py", line 135, in <module>
          raise ImportError(msg) from e
      ImportError: Error importing numpy: you should not try to import numpy from
              its source directory; please exit the numpy source tree, and relaunch
              your python interpreter from there.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip
```

**Comment by YuChuXi** [comment]
可以试着安装libgcc-[9/10/11/12]-dev
